import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { Nav, NavLink } from "@/components/Nav";

import { Facebook, Instagram, Mail, Phone, Send } from "lucide-react";
import Link from "next/link";
import { Header } from "./header";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          inter.variable
        )}
      >
        <div className="sticky top-0 flex flex-col lg:flex-row bg-white z-50">
          <Header />

          <div className="w-full flex-col">
            <div className="bg-white hidden lg:flex lg:justify-between">
              <div className="px-5 text-left flex flex-col lg:flex-row">
                <div className="h-full inline-flex items-center py-2 mr-4">
                  <Mail className="text-primary-text" />
                  <p className="mb-0">info@example.com</p>
                </div>
                <div className="h-full inline-flex items-center py-2">
                  <Phone className="text-primary-text" />
                  <p className="mb-0">+012 345 6789</p>
                </div>
              </div>
              <div className="px-5 text-right hidden lg:flex">
                <div className="inline-flex items-center py-2">
                  <Link
                    className="mr-3 text-primary-text hover:bg-primary-text hover:text-secondary-text transition-colors duration-300"
                    href=""
                  >
                    <Facebook />
                  </Link>
                  <Link
                    className="mr-3 text-primary-text hover:bg-primary-text hover:text-secondary-text transition-colors duration-300"
                    href=""
                  >
                    <Instagram />
                  </Link>
                  <Link
                    className="mr-3 text-primary-text hover:bg-primary-text hover:text-secondary-text transition-colors duration-300"
                    href=""
                  >
                    <Send />
                  </Link>
                </div>
              </div>
            </div>

            <Nav className="hidden lg:flex">
              <NavLink href="/">Home</NavLink>
              <NavLink href="/products">Products</NavLink>
              <NavLink href="/users">Customers</NavLink>
              <NavLink href="/orders">Sales</NavLink>
            </Nav>
          </div>
        </div>

        <div className="container px-0">{children}</div>
      </body>
    </html>
  );
}
